Default: &defaults
  database: loyly.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: loyly_test.sqlite3
  <<: *defaults

Staging:
  database: loyly_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: loyly_production.sqlite3
  poolsize: 100
  <<: *defaults
